baseURL = "https://www.schlatter.net/"
languageCode = "en-us"
title = "schlatter.net"

theme = "bootstrap"

enableGitInfo = true

[blackfriday]
  hrefTargetBlank = true

[params]
  author = "Christian Schlatter"
